Mess Menagement System(MMS)/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', function () {
    return view('home.home');
});

Route::GET('bill_collection_index', 'mess\AjexController@bill_collection_index');
Route::GET('advanced_index', 'mess\AjexController@advanced_index');
Route::GET('member_wise_bills', 'mess\AjexController@member_wise_bill');
Route::GET('member_wise_result', 'mess\AjexController@member_wise_result');



Route::resource('members','mess\MemberController');
Route::resource('rooms','mess\RoomController');
Route::resource('allocate_rooms','mess\AllocateRoomController');
Route::resource('bill_categorys','mess\BillCategoryController');
Route::resource('bill_collections','mess\MonthlyBillCollection');
Route::resource('advanced_collections','mess\AdvancedCollectionController');

Route::get('profile', ['middleware' => 'auth', function() {


}]);
/*
 * dining 
 */
Route::resource('dining_members','dining\MemberController');
Route::resource('dining_diposit_withdraw','dining\DipositWithdrawController');
Route::resource('dining_cost','dining\CostController');
Route::resource('dining_meals','dining\MealController');
Route::resource('dining_closing_date','dining\ClosingDateController');
/*
 * dining report
 */
Route::GET('dining_cost_rechived_payment', 'dining\ReportController@cost_rechived_payment');
Route::GET('dining_member_wise_report', 'dining\ReportController@member_wise_report');

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

Mess Menagement System(MMS)/resources/views/layout/_footer.blade.php
<div class="row">
          <div class="col-md-12 text-center font-size-bold" style="height: 60px;background-color:#737373;color: #EEE;margin-bottom: 5px">
              <h2>Mess Manegment System !</h2>
          </div>
      </div>

Mess Menagement System(MMS)/resources/views/layout/_head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}" />
<title>MMS || @yield('title')</title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="/css/sideber.css" rel="stylesheet" type="text/css"/>
<link href="/css/nav.css" rel="stylesheet" type="text/css"/>
<link href="/css/main.css" rel="stylesheet" type="text/css"/>

Mess Menagement System(MMS)/resources/views/layout/_header.blade.php
<div class="row">
    <div class="col-md-12" style="height: 60px;background-color:#EEE;color: #269abc;margin-bottom: 0px">
      
<!--            <div class="col-md-10 font-size-bold text-center ">
               
                <h2>Mess Manegment System !</h2>
            </div>-->
      <div class="col-md-10 font-size-bold text-center">
           <h2>Mess Manegment System !</h2>
            </div>  
<div class="col-md-2" style="text-align:right">
    <h6> <a href="https://www.facebook.com"><img src="/img/fb.png" alt="" style="height: 40px;width: 40px"/></a></h6> 
    
</div>

        
    </div>
</div>

Mess Menagement System(MMS)/resources/views/layout/_js.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script>
    //sideber
    $(document).ready(function(){
        $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            //---------
        $('.has-sub').click(function(){
             $('.has-sub').removeClass('tap');
            $(this).addClass('tap');
        });
        //allocate room list
        $('#present_cond').click(function(){
            var button = $('#present_cond').html();
            
            console.log(button);
            if(button == 'RUNNING'){
                $('#present_cond').html('RELEASES');
                $('#present_cond').removeClass('btn btn-primary');
                $('#present_cond').addClass('btn btn-danger');
                $('.running').show();
                $('.releases').hide();
            }else{
                $('#present_cond').html('RUNNING');
                $('#present_cond').removeClass('btn btn-danger');
                $('#present_cond').addClass('btn btn-primary');
                $('.running').hide();
                $('.releases').show();
            }
            
        });


        //bill_collection_index
            $('#bill_collection_index').on('click', function () {
                $.ajax({
                    url: "{{action('mess\AjexController@bill_collection_index')}}",
                    type: "GET",
                    async: false,
                    data: $("#form").serialize(),
                    success: function (data) {
//                         console.log(data);
                         $("#showme").html(data);
                    }
                });
            });
         //advanced_index
            $('#advanced_index').on('change',function () {
                $.ajax({
                    url: "{{action('mess\AjexController@advanced_index')}}",
                    type: "GET",
                    async: false,
                    data: {
                        id:$('#advanced_index').val()
                    },
                    success: function (data) {
//                         console.log(data);
                         $("#result").html(data);
                    }
                });
            });
            //member_wise_result
            $('#member_wise_result').on('click', function () {
                $.ajax({
                    url: "{{action('mess\AjexController@member_wise_result')}}",
                    type: "GET",
                    async: false,
                    data: $("#form").serialize(),
                    success: function (data) {
//                         console.log(data);
                         $("#result").html(data);
                    }
                });
            });
            /*
             * daining
             */
            // daining_meal_add_input
            
            var i = 1;
            $('#add').click(function(){
                i++;
                 var form = '';
                      form +='<div class="form-group" id="row'+i+'">';
                      form +='<div class="col-sm-3 control-label" style="font-weight:bold">Member Code :</div>';
                      form +='<div class="col-sm-4">';
                      form +='<select class="form-control" id="member_id" name="member_id[]">';
                       @if(isset($meal_members)) 
                           @foreach($meal_members as $meal_member)
                           form +='<option value="'+{{$meal_member->member_id}}+'">'+'{{$meal_member->members->code_no}}'+' ( {{$meal_member->members->name}} )'+'</option>';
                           @endforeach
                       @endif
                      form +='</select>';
                      form +='</div>';
                      form +='<div class="col-sm-3">';
                      form +='<input type="number" class="form-control" min=1 max=10 required="" id="no_of_meal" name="no_of_meal[]" placeholder="no of meal">';
                      form +='</div>';
                      form +='<div class="col-sm-1">';
                      form +='<span class="glyphicon glyphicon-minus btn btn-sm btn-danger btn-remove" aria-hidden="true" id="'+i+'"></span>';
                      form +='</div>';
                      form +='</div>';        
                $('.add_fild').append(form);
            });
            $(document).on('click','.btn-remove',function(){
                var button_id = $(this).attr('id');
                $('#row'+button_id+'').remove();
            });
            
    })
</script>
    

Mess Menagement System(MMS)/resources/views/layout/_msg.blade.php
@if(Session::has('success'))
<div class="alert alert-success" role="alert">
    <strong>Success:</strong>{{Session::get('success')}}
</div>
@endif
@if(Session::has('fails'))
<div class="alert alert-danger" role="alert">
    <strong>Failds:</strong>{{Session::get('fails')}}
</div>
@endif
@if(count($errors)>0)
<div class="alert alert-danger" role="alert">
    <strong>Errors:
        <ul>
            @foreach($errors->all() as $error)
            <li>{{$error}}</li>
            @endforeach
        </ul>
</div>
@endif

Mess Menagement System(MMS)/resources/views/layout/_nav.blade.php
<nav class="navbar navbar-inverse" style="background-color:#EEE;" >

    <div class="container-fluid" >
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
         <!--Collect the nav links, forms, and other content for toggling--> 
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"  >
            <ul class="nav nav-tabs" >
                <li class="#"><a style="font-weight: bold;" href="{{url('/')}}">Home <span class="sr-only">(current)</span></a></li>
                <li class="dropdown" >
                    <a style="font-weight: bold;" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">MESS <span class="caret"></span></a>
                    <ul class="dropdown-menu" >
                        <li><a href="{{route('members.index')}}">Member List</a></li>
                        <li><a href="{{route('allocate_rooms.index')}}">Allocate Room</a></li>
                        <li><a href="{{route('bill_collections.index')}}">Indivisul Bill</a></li>
                        <li><a href="{{route('advanced_collections.index')}}">Advanced</a></li>
                         <li><a href="{{url('member_wise_bills')}}">Member_wise_bills</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a style="font-weight: bold;" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Daining<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{route('dining_members.index')}}">Member List</a></li>
                        <li><a href="{{route('dining_diposit_withdraw.index')}}">Cash Recived & Payment</a></li>
                        <li><a href="{{route('dining_cost.index')}}">Cost</a></li>
                        <li><a href="{{route('dining_meals.index')}}">Meals</a></li>
                        <li style="text-align: center;font-weight: bold;background-color: #269abc">report</li>
                      
                        <li><a href="{{url('dining_cost_rechived_payment')}}">Report Of Cash</a></li>
                        <li><a href="{{url('dining_member_wise_report')}}">Monthly Report</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

Mess Menagement System(MMS)/resources/views/layout/_sideber.blade.php
<div class="col-md-3" >
    <div class=""style="min-height: 600px;">
        <div class="text-center text-capitalize" style="color: #EEE;background-color: #737373;padding: 5px">
            <h3>Menu</h3>
        </div>
        <hr/>
        <div class="main-sid" style="">
            <ul class="main-sid-ul">
                <li class="has-sub"><a class="a" href="/">HOME</a>    
                </li>
                @if(Auth::check())
                <li class="has-sub"><a class="a" href="#"><span class="sub-arrow">MESS</span></a>
                    <ul>
                        <li><a href="{{Route('members.create')}}">JOIN MEMBER</a></li>
                        <li><a href="{{Route('rooms.create')}}">ADD NEW ROOM</a></li>
                        <li><a href="{{Route('allocate_rooms.create')}}">ALLOCATED ROOM</a></li>
                        <li><a href="{{Route('bill_categorys.create')}}">ADD BILL CATEGORY</a></li>
                        <li><a href="{{Route('bill_collections.create')}}">COLLECTION BILL</a></li>
                        <li><a href="{{Route('advanced_collections.create')}}">ADVANCED COLLECT</a></li>
                    </ul>    
                </li>
                <li class="has-sub"><a class="a" href="#"><span class="sub-arrow">DAINING</span></a>
                    <ul>
                        <li><a href="{{Route('dining_members.create')}}">JOIN MEMBER</a></li>
                        <li><a href="{{Route('dining_diposit_withdraw.create')}}">DIPOSIT OR WITHDRAW</a></li>
                        <li><a href="{{Route('dining_cost.create')}}">Cost Entry</a></li>
                        <li><a href="{{Route('dining_meals.create')}}">Meal Entry Form</a></li>
                        <li><a href="{{Route('dining_closing_date.create')}}">SET CLOSING DATE*</a></li>
                    </ul>    
                </li>
                @endif
                @if(!Auth::check())
                <li class="has-sub"><a class="a" href="{{url('auth/register')}}">REGISTION</a>   
                <li class="has-sub"><a class="a" href="{{url('auth/login')}}">LOGIN</a>
                @else
                <li class="has-sub"><a class="a" href="{{url('auth/logout')}}">LOGOUT</a>
                @endif      
            </ul>
        </div>
    </div>
</div>